export const AudioEvents = {
  ON_PLAY: 'ON_PLAY',
  ON_PROGRESS: 'ON_PROGRESS',
  ON_STOP: 'ON_STOP',
  ON_END: 'ON_END',
  ON_ERROR: 'ON_ERROR',
  ON_TRACK_CHANGE: 'ON_TRACK_CHANGE',
  ON_PAUSE: 'ON_PAUSE',
  ON_READY: 'ON_READY',
  ON_LOAD: 'ON_LOAD',
  ON_QUEUE_END: 'ON_QUEUE_END',
  ON_METADATA_RECEIVED: 'ON_METADATA_RECEIVED',
} as const;

export const RemoteEvents = {
  ON_REMOTE_PLAY: 'ON_REMOTE_PLAY',
  ON_REMOTE_PAUSE: 'ON_REMOTE_PAUSE',
  ON_REMOTE_NEXT: 'ON_REMOTE_NEXT',
  ON_REMOTE_PREVIOUS: 'ON_REMOTE_PREVIOUS',
  ON_REMOTE_JUMP_BACKWARD: 'ON_REMOTE_JUMP_BACKWARD',
  ON_REMOTE_JUMP_FORWARD: 'ON_REMOTE_JUMP_FORWARD',
  ON_REMOTE_SEEK: 'ON_REMOTE_SEEK',
  ON_REMOTE_DUCK: 'ON_REMOTE_DUCK',
} as const;

export type RemoteEvents = keyof typeof RemoteEvents;
export type AudioEvents = keyof typeof AudioEvents;
